### ISSUE TITLE
Keep container running (e.g.) with Docker Compose

### ISSUE THREAD

**Issue by bittner** [themattrix/docker-tox#8]
I would like to just start up the Python-Tox container (via `docker-compose up`) and have it sit there waiting for `docker-compose run` commands to come along. The container would then behave like a local CI/build server.

Would that be a valid use case for this image, or is it meant to really run `tox` at build time only?
# Related docker-compose Configuration

This example is using Docker Compose v1 syntax:

``` YAML
# -- content of: docker-compose.yml
app:
  image: themattrix/tox
  volumes:
    - .:/app
  command: 'tox'  # optional
```

When I run `docker-compose up` Tox runs the tests, then the container exits immediately.
